import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fb' },
  header: { paddingTop: 52, paddingHorizontal: 18, paddingBottom: 12, backgroundColor: '#fff' },
  title: { fontSize: 24, color: '#202124', fontWeight: '900' },
  subtitle: { color: '#5f6368', marginTop: 3 },
  filters: { flexGrow: 0, paddingVertical: 10, paddingLeft: 14 },
  filterChip: { backgroundColor: '#fff', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 18, marginRight: 7, borderWidth: 1, borderColor: '#dadce0' },
  filterChipActive: { backgroundColor: '#1a73e8', borderColor: '#1a73e8' },
  filterText: { color: '#3c4043', fontWeight: '700', fontSize: 12 },
  filterTextActive: { color: '#fff' },
  list: { padding: 14, paddingBottom: 110 },
  empty: { color: '#5f6368', textAlign: 'center', marginTop: 60 },
  card: { backgroundColor: '#fff', borderRadius: 18, marginBottom: 15, overflow: 'hidden', elevation: 3 },
  image: { width: '100%', height: 170 },
  placeholder: { height: 110, backgroundColor: '#e8f0fe', justifyContent: 'center', alignItems: 'center' },
  placeholderIcon: { fontSize: 42 },
  cardBody: { padding: 15 },
  cardTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  cardTitle: { flex: 1, color: '#202124', fontSize: 18, fontWeight: '900' },
  status: { fontWeight: '900', fontSize: 12 },
  category: { color: '#1a73e8', fontSize: 12, fontWeight: '800', marginTop: 2 },
  address: { color: '#3c4043', marginTop: 9, lineHeight: 19 },
  distance: { color: '#137333', fontSize: 12, fontWeight: '800', marginTop: 4 },
  info: { color: '#5f6368', fontSize: 12, marginTop: 5 },
  tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 10 },
  tag: { color: '#3c4043', backgroundColor: '#f1f3f4', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 9, fontSize: 11, fontWeight: '700' },
  routeButton: { backgroundColor: '#1a73e8', padding: 12, borderRadius: 12, alignItems: 'center', marginTop: 13 },
  routeText: { color: '#fff', fontWeight: '900' },
  adminActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 10 },
  editButton: { backgroundColor: '#e8f0fe', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 10 },
  editText: { color: '#1a73e8', fontWeight: '800' },
  deleteButton: { backgroundColor: '#fce8e6', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 10 },
  deleteText: { color: '#c5221f', fontWeight: '800' },
  addButton: { position: 'absolute', right: 18, bottom: 108, width: 58, height: 58, borderRadius: 29, backgroundColor: '#1a73e8', alignItems: 'center', justifyContent: 'center', elevation: 8 },
  addText: { color: '#fff', fontSize: 34 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end' },
  modalBox: { maxHeight: '92%', backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20 },
  modalTitle: { fontSize: 22, fontWeight: '900', color: '#202124', marginBottom: 15 },
  input: { borderWidth: 1, borderColor: '#dadce0', borderRadius: 12, padding: 12, marginBottom: 10, color: '#202124' },
  searchInput: { borderWidth: 1, borderColor: '#9aa0a6', borderRadius: 12, padding: 12, color: '#202124' },
  searchButton: { backgroundColor: '#1a73e8', padding: 12, borderRadius: 12, alignItems: 'center', marginTop: 8, marginBottom: 8 },
  searchButtonText: { color: '#fff', fontWeight: '900' },
  searchResult: { flexDirection: 'row', alignItems: 'flex-start', borderWidth: 1, borderColor: '#dadce0', backgroundColor: '#fff', padding: 11, borderRadius: 12, marginBottom: 7 },
  searchResultIcon: { fontSize: 18, marginRight: 8 },
  searchResultBody: { flex: 1 },
  searchResultText: { color: '#202124', fontSize: 13, lineHeight: 18, fontWeight: '700' },
  searchResultHint: { color: '#1a73e8', fontSize: 11, marginTop: 3, fontWeight: '700' },
  selectedAddress: { backgroundColor: '#e6f4ea', borderWidth: 1, borderColor: '#81c995', padding: 11, borderRadius: 12, marginBottom: 5 },
  selectedAddressTitle: { color: '#137333', fontWeight: '900', fontSize: 12 },
  selectedAddressText: { color: '#3c4043', fontSize: 12, lineHeight: 17, marginTop: 3 },
  attribution: { color: '#80868b', fontSize: 10, marginBottom: 10 },
  label: { color: '#5f6368', fontWeight: '800', fontSize: 13, marginTop: 4, marginBottom: 6 },
  options: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 11 },
  option: { backgroundColor: '#f1f3f4', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 10 },
  optionActive: { backgroundColor: '#1a73e8' },
  optionText: { color: '#3c4043', fontWeight: '700', fontSize: 12 },
  optionTextActive: { color: '#fff' },
  switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 7 },
  switchLabel: { color: '#3c4043', fontWeight: '700' },
  preview: { width: '100%', height: 170, borderRadius: 13, marginTop: 8 },
  photoActions: { flexDirection: 'row', gap: 8, marginTop: 10 },
  photoButton: { flex: 1, backgroundColor: '#e8f0fe', padding: 11, borderRadius: 11, alignItems: 'center' },
  photoText: { color: '#1a73e8', fontWeight: '800' },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 18, marginBottom: 14 },
  cancelButton: { backgroundColor: '#f1f3f4', paddingHorizontal: 16, paddingVertical: 11, borderRadius: 11 },
  cancelText: { color: '#3c4043', fontWeight: '800' },
  saveButton: { backgroundColor: '#1a73e8', paddingHorizontal: 18, paddingVertical: 11, borderRadius: 11 },
  saveText: { color: '#fff', fontWeight: '900' },
});
