import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fb' }, content: { padding: 17, paddingTop: 50, paddingBottom: 120 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f5f7fb' }, loading: { color: '#5f6368', marginTop: 10 },
  title: { color: '#202124', fontSize: 27, fontWeight: '900' }, subtitle: { color: '#5f6368', lineHeight: 20, marginTop: 6, marginBottom: 17 },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, summaryCard: { width: '48%', minHeight: 108, borderRadius: 16, padding: 14, justifyContent: 'space-between', borderWidth: 1 }, blueCard: { backgroundColor: '#e8f0fe', borderColor: '#aecbfa' }, greenCard: { backgroundColor: '#e6f4ea', borderColor: '#a8dab5' }, redCard: { backgroundColor: '#fce8e6', borderColor: '#f4c7c3' }, grayCard: { backgroundColor: '#f1f3f4', borderColor: '#dadce0' }, summaryNumber: { color: '#202124', fontSize: 30, fontWeight: '900' }, summaryLabel: { color: '#3c4043', fontSize: 12, fontWeight: '800', lineHeight: 16 },
  recentBox: { backgroundColor: '#1a73e8', borderRadius: 16, padding: 15, marginTop: 12, flexDirection: 'row', alignItems: 'center', gap: 13 }, recentNumber: { color: '#fff', fontSize: 34, fontWeight: '900' }, recentTitle: { color: '#fff', fontWeight: '900' }, recentText: { color: '#d2e3fc', fontSize: 11, lineHeight: 15, marginTop: 2 },
  section: { backgroundColor: '#fff', borderRadius: 17, padding: 15, marginTop: 13, borderWidth: 1, borderColor: '#e1e5ea' }, sectionTitle: { color: '#202124', fontSize: 17, fontWeight: '900', marginBottom: 12 },
  mapHelp: { color: '#5f6368', fontSize: 11, lineHeight: 16, marginTop: -6, marginBottom: 10 }, heatmap: { width: '100%', height: 245, borderRadius: 13, overflow: 'hidden' }, mapGradient: { flexDirection: 'row', height: 10, borderRadius: 5, overflow: 'hidden', marginTop: 10 }, mapColor: { flex: 1 }, mapLegendLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 }, mapLegendText: { color: '#5f6368', fontSize: 9 }, mapCount: { color: '#3c4043', fontSize: 11, fontWeight: '800', marginTop: 7 },
  barItem: { marginBottom: 11 }, barHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 }, barLabel: { color: '#3c4043', fontSize: 12, fontWeight: '700' }, barValue: { color: '#202124', fontSize: 12, fontWeight: '900' }, barTrack: { height: 9, backgroundColor: '#f1f3f4', borderRadius: 5, overflow: 'hidden' }, barFill: { height: '100%', borderRadius: 5 }, empty: { color: '#80868b', fontStyle: 'italic' },
  privacyBox: { backgroundColor: '#eef6ff', borderWidth: 1, borderColor: '#d2e3fc', borderRadius: 15, padding: 13, marginTop: 13 }, privacyTitle: { color: '#174ea6', fontWeight: '900' }, privacyText: { color: '#3c4043', fontSize: 11, lineHeight: 17, marginTop: 4 },
});
