import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f4f6f9' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { paddingTop: 60, paddingBottom: 16, paddingHorizontal: 20, backgroundColor: '#fff', borderBottomWidth: 1, borderColor: '#eef2f5' },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  filterToggle: { backgroundColor: '#e8f0fe', paddingHorizontal: 11, paddingVertical: 9, borderRadius: 11 },
  filterToggleText: { color: '#1a73e8', fontSize: 12, fontWeight: '900' },
  title: { fontSize: 24, fontWeight: 'bold', color: '#1a1c1e' },
  subtitle: { fontSize: 13, color: '#6c757d', marginTop: 2 },
  emptyText: { fontSize: 16, color: '#5f6368', fontWeight: '500' },
  filteredEmpty: { alignItems: 'center', gap: 10, paddingVertical: 45 },
  filtersBox: { backgroundColor: '#fff', maxHeight: 315, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#e1e5ea' },
  filterHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  filterTitle: { color: '#202124', fontSize: 16, fontWeight: '900' },
  clearFilters: { color: '#1a73e8', fontWeight: '800' },
  filterLabel: { color: '#5f6368', fontSize: 12, fontWeight: '800', marginTop: 9, marginBottom: 5 },
  filterInput: { borderWidth: 1, borderColor: '#dadce0', borderRadius: 11, paddingHorizontal: 11, paddingVertical: 8, color: '#202124' },
  filterChip: { backgroundColor: '#f1f3f4', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10, marginRight: 6 },
  filterChipActive: { backgroundColor: '#1a73e8' },
  filterChipText: { color: '#3c4043', fontSize: 11, fontWeight: '700' },
  filterChipTextActive: { color: '#fff' },
  filterWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  resultsCount: { color: '#137333', fontSize: 11, fontWeight: '800', marginTop: 10, marginBottom: 4 },
  card: { backgroundColor: '#fff', borderRadius: 16, marginBottom: 16, overflow: 'hidden', elevation: 4, shadowColor: '#000', shadowOpacity: 0.06, shadowRadius: 6 },
  cardImage: { width: '100%', height: 200, resizeMode: 'cover' },
  noImagePlaceholder: { width: '100%', height: 100, backgroundColor: '#e9ecef', justifyContent: 'center', alignItems: 'center', gap: 4 },
  noImageText: { fontSize: 12, color: '#6c757d', fontWeight: '600' },
  cardContent: { padding: 16 },
  statusBadge: { alignSelf: 'flex-start', fontSize: 10, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginBottom: 6, overflow: 'hidden' },
  statusActive: { color: '#137333', backgroundColor: '#e6f4ea' },
  statusClosed: { color: '#5f6368', backgroundColor: '#f1f3f4' },
  officialBadge: { alignSelf: 'flex-start', color: '#1a73e8', backgroundColor: '#e8f0fe', fontSize: 10, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginBottom: 10, overflow: 'hidden' },
  previousBadge: { alignSelf: 'flex-start', color: '#5f6368', backgroundColor: '#f1f3f4', fontSize: 10, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, marginBottom: 10, overflow: 'hidden' },
  cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  cardTitle: { fontSize: 18, fontWeight: '700', color: '#1a1c1e' },
  cardTime: { fontSize: 12, color: '#1a73e8', fontWeight: '600', backgroundColor: '#e8f0fe', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  cardDescription: { fontSize: 14, color: '#3c4043', lineHeight: 22, marginBottom: 12 },
  neighborhood: { color: '#5f6368', fontSize: 12, fontWeight: '700', marginBottom: 10 },
  riskRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  riskBadge: { fontSize: 13, fontWeight: '900' },
  radiusText: { fontSize: 12, color: '#5f6368', fontWeight: '700' },
  guidanceBox: { backgroundColor: '#eef6ff', borderRadius: 12, padding: 11, marginBottom: 12 },
  guidanceTitle: { color: '#202124', fontWeight: '800', fontSize: 13 },
  guidanceText: { color: '#5f6368', fontSize: 12, lineHeight: 18, marginTop: 3 },
  cardFooter: { borderTopWidth: 1, borderTopColor: '#f1f3f4', paddingTop: 10 },
  cardUser: { fontSize: 12, color: '#747775', fontStyle: 'italic' },
  cardDate: { fontSize: 11, color: '#80868b', marginTop: 3 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', gap: 8, marginTop: 12 },
  detailsAction: { backgroundColor: '#f1f3f4', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 10 },
  detailsActionText: { color: '#3c4043', fontWeight: '800' },
  editAction: { backgroundColor: '#e8f0fe', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 10 },
  editActionText: { color: '#1a73e8', fontWeight: '800' },
  closeAction: { backgroundColor: '#e6f4ea', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 10 },
  closeActionText: { color: '#137333', fontWeight: '800' },
  statusModalOverlay: { flex: 1, justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.5)', padding: 18 },
  statusModalBox: { backgroundColor: '#fff', borderRadius: 22, padding: 20, maxHeight: '90%' },
  statusModalSubtitle: { color: '#5f6368', fontSize: 12, lineHeight: 18, marginBottom: 12 },
  statusChoice: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#e1e5ea', borderRadius: 13, padding: 12, marginBottom: 8 },
  statusChoiceEmoji: { fontSize: 21 },
  statusChoiceLabel: { color: '#202124', fontSize: 14, fontWeight: '900' },
  statusChoiceDescription: { color: '#5f6368', fontSize: 10, lineHeight: 15, marginTop: 2 },
  statusCurrentMark: { fontSize: 9, fontWeight: '900' },
  statusCancel: { alignSelf: 'center', backgroundColor: '#f1f3f4', paddingHorizontal: 24, paddingVertical: 11, borderRadius: 11, marginTop: 7 },
  deleteAction: { backgroundColor: '#fce8e6', paddingHorizontal: 13, paddingVertical: 9, borderRadius: 10 },
  deleteActionText: { color: '#c5221f', fontWeight: '800' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.4)' },
  modalBox: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, maxHeight: '85%' },
  modalTitle: { fontSize: 22, fontWeight: '900', color: '#202124', marginBottom: 14 },
  modalLabel: { color: '#5f6368', fontSize: 13, fontWeight: '800', marginTop: 8, marginBottom: 6 },
  modalInput: { minHeight: 90, borderWidth: 1, borderColor: '#dadce0', borderRadius: 12, padding: 12, textAlignVertical: 'top', color: '#202124' },
  modalNeighborhoodInput: { borderWidth: 1, borderColor: '#dadce0', borderRadius: 12, padding: 12, color: '#202124' },
  optionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 8 },
  option: { backgroundColor: '#f1f3f4', paddingHorizontal: 11, paddingVertical: 9, borderRadius: 11 },
  optionSelected: { backgroundColor: '#1a73e8' },
  optionText: { color: '#202124', fontWeight: '700', fontSize: 12 },
  optionTextActive: { color: '#fff' },
  reactivateNote: { color: '#8a3b00', backgroundColor: '#fff4e5', padding: 10, borderRadius: 10, fontSize: 11, marginTop: 8 },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 18 },
  modalCancel: { backgroundColor: '#f1f3f4', paddingHorizontal: 16, paddingVertical: 11, borderRadius: 11 },
  modalCancelText: { color: '#3c4043', fontWeight: '800' },
  modalSave: { backgroundColor: '#1a73e8', paddingHorizontal: 18, paddingVertical: 11, borderRadius: 11 },
  modalSaveText: { color: '#fff', fontWeight: '900' }
});

export default styles;
