import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  map: { flex: 1 },
  searchBox: {
    position: 'absolute', top: 48, left: 14, right: 14, backgroundColor: '#fff', borderRadius: 28,
    paddingVertical: 8, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10,
    elevation: 7, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 8,
  },
  avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#e8f0fe', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#1a73e8', fontWeight: 'bold' },
  searchTitle: { fontSize: 16, fontWeight: '700', color: '#202124' },
  searchSub: { fontSize: 12, color: '#5f6368', marginTop: 1 },
  config: { fontSize: 22 },
  filterBar: { position: 'absolute', top: 112, left: 14, right: 0 },
  chip: { backgroundColor: '#fff', paddingHorizontal: 14, paddingVertical: 9, borderRadius: 22, marginRight: 8, elevation: 4 },
  chipText: { color: '#202124', fontWeight: '600' },
  heatmapChipActive: { backgroundColor: '#d93025' },
  heatmapLegend: { position: 'absolute', left: 14, bottom: 145, width: 190, backgroundColor: 'rgba(255,255,255,0.96)', padding: 11, borderRadius: 13, elevation: 7 },
  heatmapLegendTitle: { color: '#202124', fontSize: 12, fontWeight: '900', marginBottom: 6 },
  heatmapGradient: { flexDirection: 'row', height: 10, overflow: 'hidden', borderRadius: 5 },
  heatmapColor: { flex: 1 },
  heatmapLegendLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 3 },
  heatmapLegendText: { color: '#5f6368', fontSize: 9 },
  heatmapCount: { color: '#3c4043', fontSize: 10, fontWeight: '700', marginTop: 5 },
  locationButton: { position: 'absolute', right: 18, bottom: 112, width: 52, height: 52, borderRadius: 26, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', elevation: 7 },
  locationText: { fontSize: 22 },
  addButton: { position: 'absolute', right: 18, bottom: 42, width: 58, height: 58, borderRadius: 29, backgroundColor: '#1a73e8', alignItems: 'center', justifyContent: 'center', elevation: 8 },
  addButtonText: { color: '#fff', fontSize: 34, marginTop: -2 },
  callout: { width: 230, backgroundColor: '#fff', borderRadius: 14, padding: 12 },
  calloutTitle: { fontSize: 16, fontWeight: 'bold', color: '#202124', marginBottom: 4 },
  severityText: { fontSize: 12, fontWeight: '800', marginBottom: 6 },
  officialBadge: { alignSelf: 'flex-start', color: '#137333', backgroundColor: '#e6f4ea', fontSize: 10, fontWeight: '900', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, marginBottom: 6 },
  previousBadge: { alignSelf: 'flex-start', color: '#5f6368', backgroundColor: '#f1f3f4', fontSize: 10, fontWeight: '900', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, marginBottom: 6 },
  calloutText: { fontSize: 14, color: '#3c4043', marginBottom: 8 },
  calloutImage: { width: '100%', height: 125, borderRadius: 10, marginBottom: 8 },
  calloutFooter: { fontSize: 11, color: '#5f6368' },
  calloutDetails: { color: '#1a73e8', fontSize: 11, fontWeight: '900', marginTop: 7, textAlign: 'center' },
  calloutDate: { fontSize: 10, color: '#747775', marginTop: 2 },
  guidanceTitle: { fontSize: 12, fontWeight: '800', color: '#202124', marginTop: 4 },
  guidanceText: { fontSize: 12, color: '#5f6368', lineHeight: 17, marginTop: 2, marginBottom: 6 },
  homeWarning: { position: 'absolute', top: 164, left: 14, right: 14, backgroundColor: '#fff4e5', borderColor: '#e8710a', borderWidth: 1, borderRadius: 14, padding: 11, elevation: 5 },
  homeWarningText: { color: '#8a3b00', fontWeight: '800', textAlign: 'center' },
  emergencyBanner: { position: 'absolute', top: 164, left: 14, right: 14, backgroundColor: '#d93025', borderRadius: 14, padding: 12, elevation: 8 },
  emergencyBannerTitle: { color: '#fff', fontWeight: '900', textAlign: 'center', fontSize: 14 },
  emergencyBannerText: { color: '#fff', textAlign: 'center', fontSize: 12, marginTop: 3 },
  weatherBox: { position: 'absolute', left: 14, bottom: 42, backgroundColor: 'rgba(255,255,255,0.96)', borderRadius: 14, paddingHorizontal: 12, paddingVertical: 9, elevation: 6, maxWidth: 230 },
  weatherTitle: { color: '#202124', fontWeight: '800', fontSize: 13 },
  weatherText: { color: '#5f6368', fontSize: 11, marginTop: 2 },
  weatherSource: { color: '#80868b', fontSize: 9, marginTop: 3 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
  modalBox: { backgroundColor: '#fff', padding: 18, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingBottom: Platform.OS === 'ios' ? 34 : 18, maxHeight: '92%' },
  dragIndicator: { width: 40, height: 5, backgroundColor: '#e0e0e0', borderRadius: 3, alignSelf: 'center', marginBottom: 10 },
  closeButtonMini: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#f1f3f4', alignItems: 'center', justifyContent: 'center' },
  modalTitle: { fontSize: 21, fontWeight: 'bold', color: '#202124' },
  sectionLabel: { fontSize: 14, fontWeight: '700', color: '#5f6368', marginTop: 8, marginBottom: 6 },
  tipoChip: { backgroundColor: '#f1f3f4', paddingHorizontal: 12, paddingVertical: 9, borderRadius: 18, marginRight: 8 },
  tipoText: { fontWeight: '600', color: '#202124' },
  optionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 10 },
  optionChip: { backgroundColor: '#f1f3f4', paddingHorizontal: 11, paddingVertical: 9, borderRadius: 12 },
  optionText: { color: '#202124', fontWeight: '700', fontSize: 13 },
  optionTextActive: { color: '#fff' },
  guidanceBox: { backgroundColor: '#eef6ff', borderRadius: 12, padding: 11, marginBottom: 12, borderWidth: 1, borderColor: '#d2e3fc' },
  emergencyAdminNotice: { backgroundColor: '#fce8e6', borderRadius: 12, padding: 11, marginBottom: 12, borderWidth: 1, borderColor: '#d93025' },
  emergencyAdminTitle: { color: '#a50e0e', fontWeight: '900', fontSize: 13 },
  emergencyAdminText: { color: '#5f2120', fontSize: 12, lineHeight: 17, marginTop: 4 },
  tempoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 14 },
  tempoChipOpcao: { backgroundColor: '#f1f3f4', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12 },
  tempoChipAtivo: { backgroundColor: '#1a73e8' },
  tempoTextoOpcao: { fontSize: 13, color: '#202124', fontWeight: '600' },
  tempoTextoAtivo: { color: '#fff' },
  input: { minHeight: 85, backgroundColor: '#f8fafd', borderRadius: 14, padding: 12, color: '#202124', textAlignVertical: 'top', borderWidth: 1, borderColor: '#e0e0e0' },
  neighborhoodInput: { backgroundColor: '#f8fafd', borderRadius: 14, padding: 12, color: '#202124', borderWidth: 1, borderColor: '#e0e0e0', marginTop: 10 },
  preview: { width: '100%', height: 170, borderRadius: 14, marginTop: 12 },
  photoRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  photoButton: { flex: 1, backgroundColor: '#e8f0fe', padding: 12, borderRadius: 12, alignItems: 'center' },
  photoText: { color: '#1a73e8', fontWeight: '700' },
  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
  modalButton: { paddingHorizontal: 18, paddingVertical: 12, borderRadius: 12 },
  cancelButton: { backgroundColor: '#f1f3f4' },
  saveButton: { backgroundColor: '#1a73e8' },
  cancelText: { color: '#202124', fontWeight: '700' },
  saveText: { color: '#fff', fontWeight: '700' },
  emergencyOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'center', padding: 16 },
  emergencyModal: { backgroundColor: '#fff', borderRadius: 22, padding: 18, maxHeight: '92%', borderTopWidth: 7, borderTopColor: '#d93025' },
  emergencyHeader: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  emergencyTitle: { color: '#b3261e', fontSize: 22, fontWeight: '900' },
  emergencySubtitle: { color: '#3c4043', fontWeight: '800', marginTop: 3 },
  emergencyClose: { width: 32, height: 32, backgroundColor: '#f1f3f4', borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  emergencyCloseText: { color: '#3c4043', fontWeight: '900' },
  emergencyDescription: { backgroundColor: '#fce8e6', color: '#5f2120', padding: 11, borderRadius: 11, lineHeight: 19, marginBottom: 12 },
  emergencySectionTitle: { color: '#202124', fontSize: 16, fontWeight: '900', marginTop: 10, marginBottom: 8 },
  emergencyItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  emergencyNumber: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#d93025', color: '#fff', textAlign: 'center', lineHeight: 24, fontWeight: '900', marginRight: 8 },
  emergencyItemText: { flex: 1, color: '#3c4043', lineHeight: 20 },
  checklistItem: { color: '#3c4043', lineHeight: 22, marginBottom: 3 },
  contactList: { gap: 8 },
  contactButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#f1f3f4', padding: 12, borderRadius: 12 },
  contactName: { color: '#202124', fontWeight: '800' },
  contactNumber: { color: '#b3261e', fontWeight: '900' },
  offlineNotice: { color: '#5f6368', backgroundColor: '#eef6ff', padding: 10, borderRadius: 10, fontSize: 12, lineHeight: 17, marginTop: 14 },
  shelterButton: { backgroundColor: '#1a73e8', borderRadius: 12, padding: 13, alignItems: 'center', marginTop: 12, marginBottom: 4 },
  shelterButtonText: { color: '#fff', fontWeight: '900' },
});

export default styles;
