import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  map: { flex: 1 },
  searchBox: {
    position: 'absolute', top: 48, left: 14, right: 14, backgroundColor: '#fff', borderRadius: 28,
    paddingVertical: 8, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10,
    elevation: 7, shadowColor: '#000', shadowOpacity: 0.16, shadowRadius: 8,
  },
  avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#e8f0fe', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#1a73e8', fontWeight: 'bold' },
  searchTitle: { fontSize: 16, fontWeight: '700', color: '#202124' },
  searchSub: { fontSize: 12, color: '#5f6368', marginTop: 1 },
  config: { fontSize: 22 },
  filterBar: { position: 'absolute', top: 112, left: 14, right: 0 },
  chip: { backgroundColor: '#fff', paddingHorizontal: 14, paddingVertical: 9, borderRadius: 22, marginRight: 8, elevation: 4 },
  chipText: { color: '#202124', fontWeight: '600' },
  locationButton: { position: 'absolute', right: 18, bottom: 112, width: 52, height: 52, borderRadius: 26, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', elevation: 7 },
  locationText: { fontSize: 22 },
  addButton: { position: 'absolute', right: 18, bottom: 42, width: 58, height: 58, borderRadius: 29, backgroundColor: '#1a73e8', alignItems: 'center', justifyContent: 'center', elevation: 8 },
  addButtonText: { color: '#fff', fontSize: 34, marginTop: -2 },
  callout: { width: 230, backgroundColor: '#fff', borderRadius: 14, padding: 12 },
  calloutTitle: { fontSize: 16, fontWeight: 'bold', color: '#202124', marginBottom: 4 },
  calloutText: { fontSize: 14, color: '#3c4043', marginBottom: 8 },
  calloutImage: { width: '100%', height: 125, borderRadius: 10, marginBottom: 8 },
  calloutFooter: { fontSize: 11, color: '#5f6368' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
  modalBox: { backgroundColor: '#fff', padding: 18, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingBottom: Platform.OS === 'ios' ? 34 : 18 },
  dragIndicator: { width: 40, height: 5, backgroundColor: '#e0e0e0', borderRadius: 3, alignSelf: 'center', marginBottom: 10 },
  closeButtonMini: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#f1f3f4', alignItems: 'center', justifyContent: 'center' },
  modalTitle: { fontSize: 21, fontWeight: 'bold', color: '#202124' },
  sectionLabel: { fontSize: 14, fontWeight: '700', color: '#5f6368', marginTop: 8, marginBottom: 6 },
  tipoChip: { backgroundColor: '#f1f3f4', paddingHorizontal: 12, paddingVertical: 9, borderRadius: 18, marginRight: 8 },
  tipoText: { fontWeight: '600', color: '#202124' },
  tempoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 14 },
  tempoChipOpcao: { backgroundColor: '#f1f3f4', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 12 },
  tempoChipAtivo: { backgroundColor: '#1a73e8' },
  tempoTextoOpcao: { fontSize: 13, color: '#202124', fontWeight: '600' },
  tempoTextoAtivo: { color: '#fff' },
  input: { minHeight: 85, backgroundColor: '#f8fafd', borderRadius: 14, padding: 12, color: '#202124', textAlignVertical: 'top', borderWidth: 1, borderColor: '#e0e0e0' },
  preview: { width: '100%', height: 170, borderRadius: 14, marginTop: 12 },
  photoRow: { flexDirection: 'row', gap: 10, marginTop: 12 },
  photoButton: { flex: 1, backgroundColor: '#e8f0fe', padding: 12, borderRadius: 12, alignItems: 'center' },
  photoText: { color: '#1a73e8', fontWeight: '700' },
  modalButtons: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 16 },
  modalButton: { paddingHorizontal: 18, paddingVertical: 12, borderRadius: 12 },
  cancelButton: { backgroundColor: '#f1f3f4' },
  saveButton: { backgroundColor: '#1a73e8' },
  cancelText: { color: '#202124', fontWeight: '700' },
  saveText: { color: '#fff', fontWeight: '700' },
});

export default styles;
