import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fb' },
  content: { paddingBottom: 40 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 25, backgroundColor: '#f5f7fb' },
  topBar: { paddingTop: 48, paddingHorizontal: 16, paddingBottom: 12, backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  topTitle: { color: '#202124', fontSize: 17, fontWeight: '900' },
  iconButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#f1f3f4', alignItems: 'center', justifyContent: 'center' },
  iconButtonText: { color: '#202124', fontSize: 30, lineHeight: 32 },
  heroImage: { width: '100%', height: 250, resizeMode: 'cover' },
  heroPlaceholder: { height: 180, backgroundColor: '#e8f0fe', alignItems: 'center', justifyContent: 'center' },
  heroEmoji: { fontSize: 54 },
  heroPlaceholderText: { color: '#5f6368', fontWeight: '700', marginTop: 5 },
  mainCard: { backgroundColor: '#fff', padding: 18, borderBottomLeftRadius: 20, borderBottomRightRadius: 20 },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  statusBadge: { fontSize: 10, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, overflow: 'hidden' },
  activeBadge: { color: '#137333', backgroundColor: '#e6f4ea' },
  closedBadge: { color: '#5f6368', backgroundColor: '#f1f3f4' },
  officialBadge: { color: '#1a73e8', backgroundColor: '#e8f0fe', fontSize: 10, fontWeight: '900', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, overflow: 'hidden' },
  type: { color: '#202124', fontSize: 25, fontWeight: '900' },
  severity: { fontSize: 14, fontWeight: '900', marginTop: 5 },
  description: { color: '#3c4043', fontSize: 15, lineHeight: 23, marginTop: 13 },
  section: { backgroundColor: '#fff', marginHorizontal: 14, marginTop: 14, padding: 15, borderRadius: 16, borderWidth: 1, borderColor: '#e1e5ea' },
  sectionTitle: { color: '#202124', fontSize: 16, fontWeight: '900', marginBottom: 8 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 15, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#f1f3f4' },
  detailLabel: { color: '#5f6368', fontSize: 12, fontWeight: '700' },
  detailValue: { flex: 1, color: '#202124', fontSize: 12, fontWeight: '700', textAlign: 'right' },
  auditItem: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#f1f3f4' },
  auditDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#1a73e8', marginTop: 4, marginRight: 10 },
  auditAction: { color: '#202124', fontWeight: '900', fontSize: 13 },
  auditAdmin: { color: '#5f6368', fontSize: 11, marginTop: 2 },
  auditDate: { color: '#80868b', fontSize: 10, marginTop: 2 },
  legacyAudit: { color: '#80868b', fontStyle: 'italic', lineHeight: 18 },
  guidanceBox: { backgroundColor: '#eef6ff', marginHorizontal: 14, marginTop: 14, padding: 15, borderRadius: 16, borderWidth: 1, borderColor: '#d2e3fc' },
  guidanceTitle: { color: '#202124', fontSize: 16, fontWeight: '900' },
  guidanceText: { color: '#3c4043', lineHeight: 21, marginTop: 6 },
  shelterLink: { backgroundColor: '#1a73e8', padding: 11, borderRadius: 11, alignItems: 'center', marginTop: 12 },
  shelterLinkText: { color: '#fff', fontWeight: '900' },
  map: { width: '100%', height: 220, borderRadius: 12, marginTop: 4 },
  coordinates: { color: '#80868b', fontSize: 10, textAlign: 'center', marginTop: 6 },
  routeButton: { backgroundColor: '#1a73e8', borderRadius: 11, padding: 12, alignItems: 'center', marginTop: 10 },
  routeButtonText: { color: '#fff', fontWeight: '900' },
  adminButton: { backgroundColor: '#202124', marginHorizontal: 14, marginTop: 14, padding: 14, borderRadius: 13, alignItems: 'center' },
  adminButtonText: { color: '#fff', fontWeight: '900' },
  notFound: { color: '#5f6368', textAlign: 'center', fontSize: 16 },
  backButton: { backgroundColor: '#1a73e8', paddingHorizontal: 20, paddingVertical: 11, borderRadius: 11, marginTop: 15 },
  backButtonText: { color: '#fff', fontWeight: '900' },
});
